# To build the image, run the following command in the terminal:
# podman build -f dockerfile_alpine -t image_alpine .

FROM docker.io/library/alpine:latest
RUN apk add --no-cache python3 py3-pip  \
    && apk add --no-cache openjdk17-jre \
    && rm -rf /var/cache/apk/*          \
    && ln -sf python3 /usr/bin/python