
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA CURLY_END CURLY_START FALSE NULL NUMBER SQUARE_END SQUARE_START STRING TRUEValue : STRING\n    | NUMBER\n    | CURLY_START Object CURLY_END\n    | SQUARE_START List SQUARE_END\n    | Bool\n    | NULL\n    \n    Bool : TRUE\n           | FALSE\n    \n    List : List COMMA Value\n           | Value\n    List : empty\n    Object : Object COMMA STRING COLON Value\n             | STRING COLON Value\n    Object : emptyempty :'
    
_lr_action_items = {'STRING':([0,4,5,17,18,20,24,],[2,11,2,21,2,2,2,]),'NUMBER':([0,5,18,20,24,],[3,3,3,3,3,]),'CURLY_START':([0,5,18,20,24,],[4,4,4,4,4,]),'SQUARE_START':([0,5,18,20,24,],[5,5,5,5,5,]),'NULL':([0,5,18,20,24,],[7,7,7,7,7,]),'TRUE':([0,5,18,20,24,],[8,8,8,8,8,]),'FALSE':([0,5,18,20,24,],[9,9,9,9,9,]),'$end':([1,2,3,6,7,8,9,16,19,],[0,-1,-2,-5,-6,-7,-8,-3,-4,]),'SQUARE_END':([2,3,5,6,7,8,9,13,14,15,16,19,23,],[-1,-2,-15,-5,-6,-7,-8,19,-10,-11,-3,-4,-9,]),'COMMA':([2,3,4,5,6,7,8,9,10,12,13,14,15,16,19,22,23,25,],[-1,-2,-15,-15,-5,-6,-7,-8,17,-14,20,-10,-11,-3,-4,-13,-9,-12,]),'CURLY_END':([2,3,4,6,7,8,9,10,12,16,19,22,25,],[-1,-2,-15,-5,-6,-7,-8,16,-14,-3,-4,-13,-12,]),'COLON':([11,21,],[18,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Value':([0,5,18,20,24,],[1,14,22,23,25,]),'Bool':([0,5,18,20,24,],[6,6,6,6,6,]),'Object':([4,],[10,]),'empty':([4,5,],[12,15,]),'List':([5,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Value","S'",1,None,None,None),
  ('Value -> STRING','Value',1,'p_Value','parser.py',98),
  ('Value -> NUMBER','Value',1,'p_Value','parser.py',99),
  ('Value -> CURLY_START Object CURLY_END','Value',3,'p_Value','parser.py',100),
  ('Value -> SQUARE_START List SQUARE_END','Value',3,'p_Value','parser.py',101),
  ('Value -> Bool','Value',1,'p_Value','parser.py',102),
  ('Value -> NULL','Value',1,'p_Value','parser.py',103),
  ('Bool -> TRUE','Bool',1,'p_Bool','parser.py',113),
  ('Bool -> FALSE','Bool',1,'p_Bool','parser.py',114),
  ('List -> List COMMA Value','List',3,'p_List','parser.py',121),
  ('List -> Value','List',1,'p_List','parser.py',122),
  ('List -> empty','List',1,'p_List_empty','parser.py',133),
  ('Object -> Object COMMA STRING COLON Value','Object',5,'p_Object','parser.py',139),
  ('Object -> STRING COLON Value','Object',3,'p_Object','parser.py',140),
  ('Object -> empty','Object',1,'p_Object_empty','parser.py',152),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',157),
]
