// +build !noasm
// Generated by PeachPy 0.2.0 from using_peachpy.py


// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB),4,$0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), BX
	ADDQ BX, AX
	MOVQ AX, ret+16(FP)
	RET
