cmake_minimum_required(VERSION 3.10)
project(CSG)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(exception_safety_example.bin exception_safety_example.cc)
add_executable(ownership_transfer_example.bin ownership_transfer_example.cc)
add_executable(counter_example.bin counter_example.cc)
add_executable(weak_ptr_example.bin weak_ptr_example.cc)
add_executable(placement_new_example.bin placement_new_example.cc)
add_executable(memory_pool_example.bin memory_pool_example.cc)
add_executable(non_owning_access_example.bin non_owning_access_example.cc)
add_executable(unique_ptr_deleter_example.bin unique_ptr_deleter_example.cc)
add_executable(raii_shared_ptr_example.bin raii_shared_ptr_example.cc)
add_executable(double_check_lock_example.bin double_check_lock_example.cc)
add_executable(crtp_example.bin crtp_example.cc)
add_executable(variant_example.bin variant_example.cc)
add_executable(opt_uniq_shared_example.bin opt_uniq_shared_example.cc)
add_executable(multiple_return_example.bin multiple_return_example.cc)
add_executable(lamda_capture.bin lamda_capture.cc)
add_executable(optional_smart_ptr_example.bin optional_smart_ptr_example.cc)