/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=dummy;dummies

// DummyResource is the Schema for the dummyresources API
type DummyResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DummyResourceSpec   `json:"spec,omitempty"`
	Status DummyResourceStatus `json:"status,omitempty"`
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *DummyResource) DeepCopyInto(out *DummyResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DummyResource) DeepCopy() *DummyResource {
	if in == nil {
		return nil
	}
	out := new(DummyResource)
	in.DeepCopyInto(out)
	return out
}

// DummyResourceSpec defines the desired state of DummyResource
type DummyResourceSpec struct {
	// Replicas is the number of dummy replicas to create
	Replicas *int32 `json:"replicas,omitempty"`

	// Message is a dummy message field
	Message string `json:"message,omitempty"`

	// Image is the container image to use
	Image string `json:"image,omitempty"`
}

// DummyResourceStatus defines the observed state of DummyResource
type DummyResourceStatus struct {
	// ObservedGeneration reflects the generation of the most recently observed DummyResource
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Phase represents the phase of the dummy resource
	Phase string `json:"phase,omitempty"`

	// Message is a status message
	Message string `json:"message,omitempty"`

	// ReadyReplicas is the number of ready replicas
	ReadyReplicas int32 `json:"readyReplicas,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DummyResourceList contains a list of DummyResource
type DummyResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DummyResource `json:"items"`
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *DummyResourceList) DeepCopyInto(out *DummyResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DummyResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DummyResourceList) DeepCopy() *DummyResourceList {
	if in == nil {
		return nil
	}
	out := new(DummyResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *DummyResourceSpec) DeepCopyInto(out *DummyResourceSpec) {
	*out = *in
	if in.Replicas != nil {
		replicasCopy := *in.Replicas
		out.Replicas = &replicasCopy
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DummyResourceSpec) DeepCopy() *DummyResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DummyResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *DummyResourceStatus) DeepCopyInto(out *DummyResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DummyResourceStatus) DeepCopy() *DummyResourceStatus {
	if in == nil {
		return nil
	}
	out := new(DummyResourceStatus)
	in.DeepCopyInto(out)
	return out
}
