// Code generated by command: go run using_avo.go -out using_avo/add_amd64.s -stubs using_avo/stub.go -pkg main. DO NOT EDIT.

package main

// Add adds two uint64 numbers using assembly.
func Add(x uint64, y uint64) uint64
